// <auto-generated />
using System;
using LojaBS.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LojaBS.Domain.Migrations
{
    [DbContext(typeof(LojaBSContext))]
    [Migration("20181106204757_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LojaBS.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf");

                    b.Property<string>("Endereco");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("LojaBS.Domain.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("descricao")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DtUltCompra")
                        .HasColumnName("dtUltCompra");

                    b.Property<DateTime>("DtUltVenda")
                        .HasColumnName("dtUltVenda");

                    b.Property<string>("UnidMedida")
                        .IsRequired()
                        .HasColumnName("um")
                        .HasMaxLength(2);

                    b.Property<double>("ValorCompra")
                        .HasColumnName("valorCompra");

                    b.Property<double>("ValorVenda")
                        .HasColumnName("valorVenda");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
